// Generated by scripts/build-pdfs.mjs — do not edit.
// PRINT_ZOOM: per-language scale that keeps the printed CV on one A4 page.
// PDF_SOURCE: hash of the files the PDFs were built from (CI checks it is current).
// PDF_VERSION: cache-busting version for the PDF downloads.
window.PRINT_ZOOM = {"es":1.03,"en":1.06,"eu":1.03,"ca":1.03,"gl":1.03,"fr":1.04,"de":1.03,"it":1.03,"pt":1.01,"nl":1.03,"sv":1.05,"no":1.04,"da":1.04,"pl":1.02,"cs":1.06,"ro":1.04,"tr":1.06,"ru":1,"uk":1.03,"zh":1.12,"ja":1.05,"ko":1.09,"ar":1.12};
window.PDF_SOURCE = '8f1851658795';
window.PDF_VERSION = '8f1851658795';
