// Pre-renders the CV as a one-page A4 PDF in every language and checks it is ATS-safe.
//
//   node build-pdfs.mjs          → writes pdf/Eneko_Ruiz_CV_XX.pdf (all languages) and print-zoom.js
//   node build-pdfs.mjs --check  → renders in memory, runs the ATS checks and fails if a committed
//                                  PDF no longer matches the site (i.e. someone forgot to rebuild)
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { PDFDocument } from 'pdf-lib';
import { ROOT, PRINT_VIEWPORT, loadTranslations, pdfPath, startServer, launch, pdfText, normalizeText } from './lib.mjs';

const CHECK = process.argv.includes('--check');
const { T, M, langs } = loadTranslations();

const KEYWORDS = ['Software Engineer', 'Full Stack', 'React', 'TypeScript', 'JavaScript', 'Node.js', 'Next.js',
  'PostgreSQL', 'Supabase', 'Firebase', 'Git', 'UPV/EHU', 'English C1', 'Basque C1'];

/** The rules a PDF must meet for ATS parsers. Returns a list of failures. */
function atsProblems(lang, { pages, text }) {
  const problems = [];
  const at = (s, from = 0) => text.indexOf(s, from);
  if (pages !== 1) problems.push(`${pages} pages (must be 1)`);
  if (M[lang].dir === 'ltr' && !text.trim().startsWith('Eneko Ruiz Mollón')) problems.push('name is not the first line');
  const order = [at('C1'), at('SST PRO DYNAMICS'), at('AG Beauty Salon'), at('Aura Health')];
  order.push(at('UPV/EHU', order[3]));
  if (order.some(i => i < 0) || order.some((i, n) => n && i <= order[n - 1])) problems.push(`reading order broken ${JSON.stringify(order)}`);
  if (/[ﬀ-ﬆ]/.test(text)) problems.push('contains ligature glyphs (ﬁ/ﬂ…) that break keyword search');
  for (const needle of ['eneekoruiz@gmail.com', '+34 600 02 51 61', 'linkedin.com/in/eneekoruiz', 'github.com/eneekoruiz']) {
    if (!text.includes(needle)) problems.push(`missing "${needle}"`);
  }
  return problems;
}

async function withMetadata(buffer, lang, title) {
  const doc = await PDFDocument.load(buffer);
  doc.setTitle(title);
  doc.setAuthor('Eneko Ruiz Mollón');
  doc.setSubject(T[lang].meta_desc);
  doc.setKeywords(KEYWORDS);
  doc.setLanguage(lang);
  doc.setCreator('eneko-cv build-pdfs');
  return Buffer.from(await doc.save());
}

const { server, origin } = await startServer();
const { browser, context } = await launch({ viewport: PRINT_VIEWPORT });
const zooms = {};
const contentHash = createHash('sha1');
const failures = [];

try {
  if (!CHECK) await mkdir(join(ROOT, 'pdf'), { recursive: true });
  for (const lang of langs) {
    const page = await context.newPage();
    await page.goto(`${origin}/?pdf=1&lang=${lang}&theme=light`, { waitUntil: 'networkidle' });
    await page.emulateMedia({ media: 'print' });
    await page.evaluate(() => document.fonts.ready);
    zooms[lang] = await page.evaluate(() => window.fitPrintToOnePage());
    const title = await page.title();
    const raw = await page.pdf({ format: 'A4', printBackground: true, preferCSSPageSize: true });
    await page.close();

    const pdf = await withMetadata(raw, lang, title);
    const parsed = await pdfText(pdf);
    const problems = atsProblems(lang, parsed);
    contentHash.update(`${lang}:${normalizeText(parsed.text)}`);

    if (CHECK) {
      const committed = pdfPath(lang);
      if (!existsSync(committed)) {
        problems.push(`missing ${committed.replace(ROOT, '')}`);
      } else if (normalizeText((await pdfText(await readFile(committed))).text) !== normalizeText(parsed.text)) {
        problems.push('committed PDF is out of date: run `npm run build` in scripts/ and commit pdf/');
      }
    } else {
      await writeFile(pdfPath(lang), pdf);
    }

    console.log(`${lang}  zoom ${zooms[lang].toFixed(2)}  ${problems.length ? '✗ ' + problems.join('; ') : '✓'}`);
    if (problems.length) failures.push(lang);
  }

  if (!CHECK) {
    await writeFile(join(ROOT, 'print-zoom.js'),
      '// Generated by scripts/build-pdfs.mjs — do not edit.\n' +
      '// PRINT_ZOOM: per-language scale that keeps the printed CV on one A4 page.\n' +
      '// PDF_VERSION: content hash of pdf/*.pdf, used to bust the download cache.\n' +
      `window.PRINT_ZOOM = ${JSON.stringify(zooms)};\n` +
      `window.PDF_VERSION = '${contentHash.digest('hex').slice(0, 10)}';\n`);
  }
} finally {
  await browser.close();
  server.close();
}

if (failures.length) {
  console.error(`\nATS/PDF checks failed for: ${failures.join(', ')}`);
  process.exit(1);
}
console.log(`\nAll ${langs.length} languages OK${CHECK ? '' : ' — PDFs written to pdf/'}.`);
